#!/bin/bash
set -eux

servers=(isu1 isu2 isu3)
appdir=/home/isucon/webapp/ruby
appuser=isucon

for server in "${servers[@]}"; do
    rsync -rv files/ "root@$server:/"
    ssh "root@$server" bash -s <<EOF
set -x
chown -R isucon $appdir
EOF

    ssh "$appuser@$server" bash -ls <<EOF
set -x
cd ${appdir}
/home/isucon/local/ruby/bin/bundle install -j2 --deployment
EOF

    ssh "root@$server" bash -s <<EOF
set -x
systemctl daemon-reload
systemctl restart isucondition.ruby.service
systemctl reload nginx
cp /var/log/nginx/access.log{,.$(date +%FT%T)}
truncate -s0 /var/log/nginx/access.log

install -o www-data -g www-data -m 0750 -d /var/cache/nginx
EOF
done

ssh "root@isu3" bash -els <<EOF
systemctl restart mysql

mysql -e "create user if not exists 'isucon'@'%' identified by 'isucon'"
mysql -e "grant all ON isucondition.* TO 'isucon'@'%'"
EOF

# rsync -rv files/etc/mysql/ "root@isucon-3:/etc/mysql/"
# ssh "root@isucon-3" bash -s <<EOF
# set -x
# systemctl restart mysql
# cp /var/log/mysql/mysql-slow.log{,.$(date +%FT%T)}
# truncate -s0 /var/log/mysql/mysql-slow.log
# EOF

# rsync -rv files/etc/mysql/ "root@isucon-2:/etc/mysql/"
# ssh "root@isucon-2" bash -s <<EOF
# set -x
# systemctl restart mysql
# cp /var/log/mysql/mysql-slow.log{,.$(date +%FT%T)}
# truncate -s0 /var/log/mysql/mysql-slow.log
# EOF
